# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160906134858 on 2016-09-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160907_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
