# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160906134858 on 2016-09-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160907_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='examen_ocular_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tratamiento_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_familiares_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_personales_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otros_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='add_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cerca_od_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cerca_oi_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='historia_clinica_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='lejos_od_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='lejos_oi_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
