# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160906134858 on 2016-09-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160907_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha_examen_text',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha examen'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacimiento_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_receta_text',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha receta'),
        ),
    ]
